### ISSUE TITLE
Feature request: Automatically find the lowest latency

### ISSUE THREAD

**Issue by esemeniuc** [spaze/oprah-proxy#2]
Hi,

It'd be super nice if the script could automatically do a couple pings to each server and automatically find the closest server.

Cheers :)

**Comment by spaze** [comment]
Hi @cwaffles and thanks for the request. I'm not exactly sure how to do that or what would be the benefit. I mean the servers can have different latency during the day so probably the geo location would be the most important here. I can try and see if I can get the closest geo location from the API and then somehow mark it in the output. Is this something you're looking for?

**Comment by esemeniuc** [comment]
Hi spaze,

The geolocation hasn't always been reliable in my experience since different providers have different routing agreements depending on your ISP. Something simple like a for loop that goes through all of the servers retrieved and pings them each 5 times or so and displays the best average at the bottom was what I had in mind.

Cheers

**Comment by spaze** [comment]
I've added listing of current location in proxy discovery call in f91c931d7e490c429b321c1715386ae83ef9c479 and listing states in 1670600c592aef994a29493883b1aa63f883f85b. Doing ICMP requires root or is platform dependent and adding this is not something I'd like to see in this simple tool. There's also a chance that the Oprah proxy will stop working completely so that seems like too much trouble. I'm closing this, sorry.

But feel free to submit a pull request with a script parsing the output and calling ping on it.

**Comment by esemeniuc** [comment]
Thanks for adding the location and listening states to the script. My python skills are a bit rusty currently, but I appreciate the effort to accommodate the request.
